const copy={
en:{brandSub:"Your pet, understood",catMeta:"Cat · 3 years",navToday:"Today",navHome:"Home mode",navDevices:"Devices",navCare:"Care plan",navInsights:"Insights",navTimeline:"Timeline",navAvatar:"3D twin studio",language:"Language",hideTwin:"Hide digital twin",showTwin:"Show digital twin",synced:"All sources synced",quickCheck:"Quick check",stableToday:"Stable today",hello:"Hello,",wellbeing:"Wellbeing",seeHome:"See what happened at home",addObservation:"Add observation",activity:"Activity",stress:"Stress",litterVisits:"Litter visits",water:"Water",baseline:"Baseline",worthKnowing:"Worth knowing",smartFinding:"One useful finding",addCareTask:"Add care task",viewEvidence:"View evidence",todayPlan:"Today’s plan",smallActions:"Small actions that help",workdayCompanion:"Workday Companion",homeWithoutWatching:"Know what matters without watching all day",homeModeCopy:"PetTwin turns device events into a calm, useful home diary.",quietMode:"Quiet",companionMode:"Companion",observeMode:"Observe",liveDiary:"Live home diary",todayAtHome:"Today at home",simulateEvent:"Simulate new event",remoteCare:"Remote care",connectGently:"Connect gently",playVoice:"Play a familiar message",smallPortion:"Dispense a limited portion",startToy:"Start a safe toy session",openCamera:"Check the living room",beforeHome:"Before you get home",deviceIntro:"Connect passive data sources so owners do less recording.",discoverDevices:"Discover devices",catOnly:"Cat intelligence",litterAnalysis:"Smart litter-box analysis",connected:"Connected",visitsToday:"Visits today",averageDuration:"Average duration",latestWeight:"Latest weight",repeatEntries:"Repeat entries",observeNotDiagnose:"Observation, not diagnosis",careIntro:"Turn insights into actions, then learn what works for this pet.",newTask:"New care task",activePlan:"Active plan",thisWeek:"This week",personalPlaybook:"Personal care playbook",behaviorBaseline:"Behavior baseline",linkedSignals:"Linked signals",environmentLinks:"Environment links",likelyTriggers:"Likely triggers",lifeArchive:"Life archive",personalityTimeline:"Personality timeline",exportReport:"Export report",digitalTwinStudio:"Digital Twin Studio",buildLookalike:"Build a 3D twin that looks like your pet",studioCopy:"Upload clear photos or use a guided phone scan. Images stay local in this prototype.",uploadPhotos:"Upload photos",uploadHint:"Front, side and coat detail",guidedScan:"Guided scan",scanHint:"Follow a 20-second capture guide",waitingInput:"Waiting for photos or scan",coatColour:"Detected coat colour",solid:"Solid",tuxedo:"Tuxedo",tabby:"Tabby",generateTwin:"Generate 3D twin",dragRotate:"The twin can roam across every page",yes:"Yes",no:"No"},
zh:{brandSub:"更懂你的宠物",catMeta:"猫 · 3 岁",navToday:"今日",navHome:"居家模式",navDevices:"设备中心",navCare:"照护计划",navInsights:"行为洞察",navTimeline:"成长档案",navAvatar:"3D 分身工作室",language:"语言",hideTwin:"隐藏数字分身",showTwin:"显示数字分身",synced:"数据源已同步",quickCheck:"快速确认",stableToday:"今日状态稳定",hello:"你好，",wellbeing:"综合状态",seeHome:"看看今天在家发生了什么",addObservation:"添加观察",activity:"活跃度",stress:"压力",litterVisits:"猫砂盆次数",water:"饮水",baseline:"接近基线",worthKnowing:"值得了解",smartFinding:"一个有用的发现",addCareTask:"加入照护任务",viewEvidence:"查看依据",todayPlan:"今日计划",smallActions:"能带来帮助的小行动",workdayCompanion:"上班陪伴模式",homeWithoutWatching:"不用一直盯着，也能知道重要变化",homeModeCopy:"PetTwin 将设备事件整理成安静而有用的居家日记。",quietMode:"安静",companionMode:"陪伴",observeMode:"密切观察",liveDiary:"实时居家日记",todayAtHome:"今天在家",simulateEvent:"模拟新事件",remoteCare:"远程照护",connectGently:"温和地保持连接",playVoice:"播放熟悉的语音",smallPortion:"投放限量零食",startToy:"开启安全玩具",openCamera:"查看客厅",beforeHome:"回家之前",deviceIntro:"连接被动数据源，让主人少记录、获得更多理解。",discoverDevices:"发现设备",catOnly:"猫咪智能分析",litterAnalysis:"智能猫砂盆分析",connected:"已连接",visitsToday:"今日次数",averageDuration:"平均停留",latestWeight:"最新体重",repeatEntries:"重复进入",observeNotDiagnose:"只做观察，不作诊断",careIntro:"把洞察变成行动，再学习什么方法真正适合它。",newTask:"新建任务",activePlan:"正在执行",thisWeek:"本周计划",personalPlaybook:"专属照护手册",behaviorBaseline:"行为基线",linkedSignals:"联动信号",environmentLinks:"环境关联",likelyTriggers:"可能的触发因素",lifeArchive:"生命档案",personalityTimeline:"人格时间轴",exportReport:"导出报告",digitalTwinStudio:"数字分身工作室",buildLookalike:"创建一只像它的 3D 数字分身",studioCopy:"上传清晰照片或使用手机引导扫描。本原型中的图片仅在本地处理。",uploadPhotos:"上传照片",uploadHint:"正面、侧面和毛色细节",guidedScan:"引导扫描",scanHint:"按照 20 秒拍摄指引操作",waitingInput:"等待照片或扫描",coatColour:"识别出的毛色",solid:"纯色",tuxedo:"燕尾服",tabby:"虎斑",generateTwin:"生成 3D 分身",dragRotate:"数字分身可以在所有页面自由活动",yes:"是的",no:"没有"}}
Object.assign(copy.en,{buildLookalike:"Create a high-fidelity digital twin",studioCopy:"Use six clear views or a guided video scan. PetTwin checks every capture before reconstruction.",captureReady:"capture ready",photoSet:"Photo set",videoScan:"Video scan",loadModel:"Load GLB",uploadPhotos:"Add pet photos",uploadHint:"Select 6-40 images. Keep the whole pet visible in even light.",guidedScan:"Start guided scan",scanHint:"A 45-second route around your pet",captureQuality:"Capture quality",stageCapture:"Capture",stageShape:"Shape",stageTexture:"Texture",stageRig:"Rig",stageReview:"Review",generateTwin:"Generate high-fidelity twin",liveModel:"LIVE MODEL",proceduralPreview:"Capture preview",waitingInput:"Add the six required views to begin",dragRotate:"Move the pointer to inspect the twin"});
Object.assign(copy.zh,{buildLookalike:"创建高还原度 3D 数字分身",studioCopy:"拍摄六个清晰视角或使用视频环绕扫描，PetTwin 会在重建前检查每一份素材。",captureReady:"采集准备度",photoSet:"照片组",videoScan:"视频扫描",loadModel:"载入 GLB",uploadPhotos:"添加宠物照片",uploadHint:"选择 6-40 张图片，使用均匀光线并保持全身入镜。",guidedScan:"开始引导扫描",scanHint:"用 45 秒绕宠物拍摄一圈",captureQuality:"采集质量",stageCapture:"采集",stageShape:"形体",stageTexture:"纹理",stageRig:"骨骼",stageReview:"验收",generateTwin:"生成高还原度分身",liveModel:"实时模型",proceduralPreview:"采集预览",waitingInput:"添加六个必需视角后开始",dragRotate:"移动指针查看数字分身"});
let lang=localStorage.getItem("pt-lang")||"en";
const defaultState={activity:72,stress:28,litter:5,repeat:2,mode:"companion",twinVisible:true,coat:"#77bed2",pattern:"solid",tasks:[{id:"play",done:false,en:"10-minute play session",zh:"互动玩耍 10 分钟",whyEn:"Activity is 8% below the evening baseline",whyZh:"晚间活跃度比基线低 8%"},{id:"water",done:true,en:"Check water level",zh:"检查饮水量",whyEn:"Completed at 12:30",whyZh:"已于 12:30 完成"},{id:"safe",done:false,en:"Prepare a quiet hiding space",zh:"准备安静的躲藏空间",whyEn:"Visitors are expected tonight",whyZh:"今晚预计有客人来访"}]};
let state=JSON.parse(localStorage.getItem("pt-state")||"null")||structuredClone(defaultState);
let coatMaterial,petGroup,headMesh,tailMesh,legs=[],worldRenderer,worldCamera,worldScene,modelMixer,modelClock,mouseX=0,activeView="today",roam=0;
const requiredViews=["Front","Left","Right","Back","Face","Coat"];
let captureResults=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],t=k=>copy[lang][k]||k,save=()=>localStorage.setItem("pt-state",JSON.stringify(state));

const eventsEn=[{time:"14:42",icon:"L",title:"Litter-box visit",detail:"54 seconds · weight 4.62 kg"},{time:"13:18",icon:"Z",title:"Nap ended",detail:"Rested for 2h 06m"},{time:"11:07",icon:"A",title:"Living-room activity",detail:"Movement returned to normal"},{time:"09:36",icon:"W",title:"Drank water",detail:"Within the usual morning range"}];
const eventsZh=[{time:"14:42",icon:"砂",title:"猫砂盆记录",detail:"停留 54 秒 · 体重 4.62 kg"},{time:"13:18",icon:"眠",title:"午睡结束",detail:"休息了 2 小时 06 分钟"},{time:"11:07",icon:"动",title:"客厅活动",detail:"活动量恢复到正常范围"},{time:"09:36",icon:"水",title:"饮水记录",detail:"处于日常早间范围"}];
const deviceData=[{icon:"LB",en:"Smart litter box",zh:"智能猫砂盆",enD:"Visits, weight and duration",zhD:"次数、体重和停留时间",connected:true},{icon:"CM",en:"Home camera",zh:"家庭摄像头",enD:"Movement and rest zones",zhD:"活动和休息区域",connected:true},{icon:"FD",en:"Smart feeder",zh:"智能喂食器",enD:"Meals and portion limits",zhD:"进食和份量限制",connected:true},{icon:"CL",en:"Activity collar",zh:"活动项圈",enD:"Activity and sleep",zhD:"活动量和睡眠",connected:false}];

function applyLanguage(){document.documentElement.lang=lang==="zh"?"zh-CN":"en";$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderAll();if($('#capture-slots'))renderCaptureSlots()}
function renderAll(){renderSummary();renderTasks();renderEvents();renderDevices();renderInsights();renderTimeline();renderPlaybook();updatePetMessage();}
function renderSummary(){const score=Math.max(45,Math.round(100-state.stress*.45-Math.max(0,70-state.activity)*.25-Math.max(0,state.litter-5)*2));$('#wellbeing-score').textContent=score;$('#activity-value').textContent=state.activity;$('#stress-value').textContent=state.stress;$('#litter-value').textContent=state.litter;$('#visits-today').textContent=state.litter;$('#repeat-entries').textContent=state.repeat;$('#daily-summary').textContent=lang==='en'?`Activity and routine are close to Mochi’s baseline. Litter-box visits are ${state.litter>5?'higher':'slightly higher'} than usual.`:`Mochi 的活动和作息接近日常基线，猫砂盆次数${state.litter>5?'明显高于':'略高于'}平时。`;$('#smart-finding').textContent=lang==='en'?"4 of Mochi’s last 5 hiding events happened after visitors arrived. Recovery usually took around 2 hours.":"Mochi 最近 5 次躲藏中，有 4 次发生在来客之后，通常需要约 2 小时恢复。";$('#litter-note').textContent=lang==='en'?"Visits are slightly above Mochi’s baseline. Continue observing drinking, appetite and repeated short visits.":"如厕次数略高于 Mochi 的日常基线，建议继续观察饮水、食欲和短时间重复进入。";$('#workday-summary').textContent=lang==='en'?"Mochi slept for 5h 48m, used the litter box several times, and played less than usual. Try a 10-minute play session tonight.":"Mochi 今天睡了约 5 小时 48 分钟，多次使用猫砂盆，玩耍比平时少。今晚可以安排 10 分钟互动。";}
function taskHTML(task,compact=false){return `<div class="task-item ${task.done?'done':''}" data-task="${task.id}"><button aria-label="Complete task">${task.done?'✓':''}</button><div><strong>${lang==='en'?task.en:task.zh}</strong><small>${lang==='en'?task.whyEn:task.whyZh}</small></div>${compact?'':`<span>${task.done?(lang==='en'?'Done':'完成'):(lang==='en'?'Planned':'计划中')}</span>`}</div>`}
function renderTasks(){const done=state.tasks.filter(x=>x.done).length;$('#task-progress').textContent=`${done}/${state.tasks.length}`;$('#compact-tasks').innerHTML=state.tasks.map(x=>taskHTML(x,true)).join('');$('#care-list').innerHTML=state.tasks.map(x=>taskHTML(x)).join('');$$('[data-task] button').forEach(btn=>btn.onclick=()=>{const task=state.tasks.find(x=>x.id===btn.parentElement.dataset.task);task.done=!task.done;if(task.done){state.activity=Math.min(100,state.activity+3);state.stress=Math.max(0,state.stress-2);petReaction('happy')}save();renderAll()})}
function renderEvents(){const data=lang==='en'?eventsEn:eventsZh;$('#event-feed').innerHTML=data.map(e=>`<div class="event-item"><span class="event-icon">${e.icon}</span><div><strong>${e.title}</strong><small>${e.time} · ${e.detail}</small></div></div>`).join('')}
function renderDevices(){$('#device-grid').innerHTML=deviceData.map((d,i)=>`<article class="device-card"><div class="device-top"><i>${d.icon}</i><span class="device-online">${d.connected?t('connected'):(lang==='en'?'Available':'可连接')}</span></div><h3>${lang==='en'?d.en:d.zh}</h3><p>${lang==='en'?d.enD:d.zhD}</p><button data-device="${i}">${d.connected?(lang==='en'?'Manage':'管理'):(lang==='en'?'Connect':'连接')}</button></article>`).join('');$$('[data-device]').forEach(b=>b.onclick=()=>{const d=deviceData[+b.dataset.device];d.connected=!d.connected;renderDevices();petReaction('curious')})}
function renderInsights(){const data=lang==='en'?[['Visitors → hiding','80% link'],['Rain → lower activity','62% link'],['Late return → vocalising','54% link'],['Clean litter → normal visits','71% link']]:[['来客 → 躲藏','关联度 80%'],['下雨 → 活跃度下降','关联度 62%'],['主人晚归 → 叫声增加','关联度 54%'],['清理猫砂 → 如厕恢复','关联度 71%']];$('#correlation-list').innerHTML=data.map(x=>`<div class="correlation-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');drawTrend()}
function renderTimeline(){const data=lang==='en'?[['Today','Workday pattern learned','Lower afternoon play may improve with a short evening session.'],['June 2026','Routine became more stable','Night vocalisation decreased and play frequency increased.'],['March 2026','Initial personality model','High curiosity, moderate sociability and strong independence.']]:[['今天','识别出新的上班日规律','下午玩耍偏少，晚间短时互动可能有帮助。'],['2026 年 6 月','作息变得更稳定','夜间叫声减少，玩耍频率增加。'],['2026 年 3 月','建立初始人格模型','高好奇、中等社交和较高独立性。']];$('#timeline-list').innerHTML=data.map(x=>`<article class="timeline-item"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}
function renderPlaybook(){const data=lang==='en'?[['Quiet hiding space','Helps'],['10-minute evening play','Helps'],['Owner voice playback','Mixed'],['Forced visitor interaction','Avoid']]:[['安静躲藏空间','有效'],['晚间玩耍 10 分钟','有效'],['播放主人语音','效果不定'],['强迫接触来客','避免']];$('#playbook').innerHTML=data.map(x=>`<div class="playbook-item"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}
function updatePetMessage(){const text=state.stress>40?(lang==='en'?"I have been a little unsettled. Could we keep tonight calm?":"我今天有一点不安，今晚可以安静一点吗？"):(lang==='en'?"I seem quieter than usual today. Does that feel right?":"我今天好像比平时安静，你也这样觉得吗？");$('#pet-message-text').textContent=text}

function navigate(view){activeView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const nav=$(`[data-view="${view}"]`);$('#page-title').textContent=nav?nav.textContent:view;$('#section-eyebrow').textContent=view==='home'?'WORKDAY COMPANION':'PETTWIN';$('#pet-message').classList.toggle('hidden',view==='avatar'||!state.twinVisible);$('#pet-message').style.visibility=view==='avatar'?'hidden':'visible';if(view==='avatar')petReaction('studio')}
$$('[data-view], [data-view-jump]').forEach(b=>b.onclick=()=>navigate(b.dataset.view||b.dataset.viewJump));$$('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem('pt-lang',lang);applyLanguage()});
$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));save();$('#remote-result').textContent=lang==='en'?`${b.textContent} notifications are now active.`:`已开启${b.textContent}通知。`});
$$('[data-signal]').forEach(b=>b.onclick=()=>{$$('[data-signal]').forEach(x=>x.classList.toggle('active',x===b));navigate(b.dataset.signal==='litter'?'devices':'insights')});
$$('[data-answer]').forEach(b=>b.onclick=()=>{state.stress=Math.max(0,state.stress+(b.dataset.answer==='yes'?2:-2));save();renderAll();petReaction(b.dataset.answer==='yes'?'calm':'curious');$('#pet-message').classList.add('hidden')});
$('#add-home-event').onclick=()=>{state.litter++;state.repeat++;eventsEn.unshift({time:new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),icon:'L',title:'Short repeat litter visit',detail:'32 seconds · worth observing'});eventsZh.unshift({time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),icon:'砂',title:'短时间重复进入猫砂盆',detail:'停留 32 秒 · 值得继续观察'});state.stress+=3;save();renderAll();petReaction('alert')};
$$('[data-remote]').forEach(b=>b.onclick=()=>{const action=b.dataset.remote;const messages={voice:['Familiar voice played once. Mochi looked toward the speaker.','已播放一次熟悉语音，Mochi 看向了扬声器。'],treat:['A 4g portion was dispensed. Daily limit: 1 remaining.','已投放 4 克零食，今日剩余限额 1 次。'],toy:['A safe 5-minute toy session has started.','已开启 5 分钟安全玩具互动。'],camera:['Camera preview would open here after device authorisation.','设备授权后将在这里打开摄像头画面。']};$('#remote-result').textContent=messages[action][lang==='en'?0:1];petReaction(action==='toy'?'happy':'curious')});
$('#discover-devices').onclick=()=>{$('#discover-devices').textContent=lang==='en'?'3 devices found':'发现 3 台设备';petReaction('curious')};
$('#new-task').onclick=()=>{const id='task'+Date.now();state.tasks.push({id,done:false,en:'Observe evening litter visits',zh:'观察今晚猫砂盆使用情况',whyEn:'Suggested after today’s repeat entries',whyZh:'根据今日重复进入记录生成'});save();renderTasks()};
$$('[data-task-add]').forEach(b=>b.onclick=()=>{if(!state.tasks.some(x=>x.id==='guest'))state.tasks.push({id:'guest',done:false,en:'Set up a visitor-safe room',zh:'准备来客时的安全房间',whyEn:'Based on hiding correlation',whyZh:'根据躲藏关联生成'});save();renderTasks();navigate('care')});
$$('[data-range]').forEach(b=>b.onclick=()=>{$$('[data-range]').forEach(x=>x.classList.toggle('active',x===b));drawTrend(+b.dataset.range)});

function drawTrend(range=7){const c=$('#trend-chart');if(!c)return;const x=c.getContext('2d'),pad=42,w=c.width-pad*2,h=c.height-pad*2;x.clearRect(0,0,c.width,c.height);x.strokeStyle='#dce5e3';for(let i=0;i<5;i++){const y=pad+i*h/4;x.beginPath();x.moveTo(pad,y);x.lineTo(c.width-pad,y);x.stroke()}const count=range===7?7:range===30?12:18;[['#75bdd0',state.activity],['#e88470',state.stress],['#84c5a1',76]].forEach(([color,base],line)=>{x.beginPath();for(let i=0;i<count;i++){const value=base+Math.sin(i*.8+line)*8+(line===1?Math.cos(i*.45)*5:0),px=pad+i*w/(count-1),py=pad+h-value*h/100;i?x.lineTo(px,py):x.moveTo(px,py)}x.strokeStyle=color;x.lineWidth=3;x.stroke()});x.lineWidth=1}

function initTwin(){const canvas=$('#pet-world');if(!window.THREE){canvas.style.display='none';return}worldScene=new THREE.Scene();worldCamera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.1,100);worldCamera.position.set(0,1.2,9);worldRenderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,preserveDrawingBuffer:true});worldRenderer.setPixelRatio(Math.min(devicePixelRatio,2));worldRenderer.shadowMap.enabled=true;petGroup=new THREE.Group();worldScene.add(petGroup);coatMaterial=new THREE.MeshStandardMaterial({color:state.coat,roughness:.78});const white=new THREE.MeshStandardMaterial({color:0xf7f7f1,roughness:.82}),dark=new THREE.MeshStandardMaterial({color:0x202a32,roughness:.55}),pink=new THREE.MeshStandardMaterial({color:0xc98282,roughness:.72});const sphere=(s,p,m=coatMaterial)=>{const o=new THREE.Mesh(new THREE.SphereGeometry(1,36,26),m);o.scale.set(...s);o.position.set(...p);o.castShadow=true;petGroup.add(o);return o};sphere([.9,.54,.52],[0,0,0]);sphere([.46,.5,.39],[.58,.08,-.08]);headMesh=sphere([.55,.5,.47],[-.7,.4,.08]);[-1,1].forEach(side=>{const ear=new THREE.Mesh(new THREE.ConeGeometry(.23,.52,4),coatMaterial);ear.position.set(-.72+side*.33,.9,.04);ear.rotation.z=side*-.14;petGroup.add(ear);sphere([.058,.078,.045],[-.72+side*.19,.49,.49],dark)});sphere([.18,.12,.08],[-.84,.24,.46],white);sphere([.18,.12,.08],[-.56,.24,.46],white);sphere([.055,.04,.04],[-.7,.28,.54],pink);sphere([.05,.018,.018],[-.7,.17,.53],dark);[[-.44,.15],[.48,.16],[-.35,-.18],[.57,-.16]].forEach(([px,pz],i)=>{const leg=sphere([.17,.36,.17],[px,-.48,pz],white);legs.push(leg);sphere([.2,.1,.2],[px,-.78,pz+.02],white)});[-1,1].forEach(side=>{for(let i=0;i<3;i++){const whisker=new THREE.Mesh(new THREE.CylinderGeometry(.008,.008,.5,8),white);whisker.position.set(-.7+side*.28,.24-i*.06,.51);whisker.rotation.z=Math.PI/2+side*(i-1)*.08;petGroup.add(whisker)}});tailMesh=new THREE.Mesh(new THREE.TorusGeometry(.47,.09,16,40,Math.PI*1.45),coatMaterial);tailMesh.position.set(.83,.2,-.08);tailMesh.rotation.set(1.4,.1,-.45);petGroup.add(tailMesh);worldScene.add(new THREE.HemisphereLight(0xffffff,0x536f68,2.8));const light=new THREE.DirectionalLight(0xffffff,3.2);light.position.set(-3,6,5);worldScene.add(light);resizeWorld();addEventListener('resize',resizeWorld);addEventListener('mousemove',e=>mouseX=(e.clientX/innerWidth-.5)*2);animateTwin()}
function resizeWorld(){if(!worldRenderer)return;worldRenderer.setSize(innerWidth,innerHeight,false);worldCamera.aspect=innerWidth/innerHeight;worldCamera.updateProjectionMatrix()}
function animateTwin(){roam+=.012;const studio=activeView==='avatar';const aspect=innerWidth/innerHeight;const span=studio?1.1:Math.min(3.9,Math.max(1.15,2.8*aspect));const targetX=studio?Math.min(2.35,3.1*aspect):Math.sin(roam*.38)*span;petGroup.position.x+=(targetX-petGroup.position.x)*.025;petGroup.position.y=studio?.35:-2.45+Math.abs(Math.sin(roam*1.7))*.07;petGroup.scale.setScalar(studio?.82:.72);petGroup.rotation.y=studio?Math.sin(roam*.4)*.5:(Math.cos(roam*.38)>0?0:Math.PI);if(headMesh)headMesh.rotation.y+=(mouseX*.28-headMesh.rotation.y)*.04;if(tailMesh)tailMesh.rotation.z=-.45+Math.sin(roam*5)*.2;legs.forEach((l,i)=>l.rotation.z=Math.sin(roam*7+i*Math.PI)*.18);if(modelMixer)modelMixer.update(modelClock.getDelta());worldRenderer.render(worldScene,worldCamera);requestAnimationFrame(animateTwin)}
function petReaction(type){if(!petGroup)return;if(type==='happy'){state.activity=Math.min(100,state.activity+1);petGroup.rotation.z=.12;setTimeout(()=>petGroup.rotation.z=0,600)}if(type==='alert'){petGroup.scale.multiplyScalar(.9)}if(type==='studio')$('#pet-message').classList.add('hidden')}
$('#pet-toggle').onclick=()=>{state.twinVisible=!state.twinVisible;$('#pet-world').style.display=state.twinVisible?'block':'none';$('#pet-message').classList.toggle('hidden',!state.twinVisible);$('#pet-toggle').textContent=state.twinVisible?t('hideTwin'):t('showTwin');save()};

function renderCaptureSlots(){const labels=lang==='en'?requiredViews:["正面","左侧","右侧","背面","脸部","毛发"];$('#capture-slots').innerHTML=labels.map((label,i)=>{const item=captureResults[i];return `<div class="capture-slot ${item?(item.pass?'good':'warn'):''}">${item?`<img src="${item.url}" alt="${label}">`:`<span>${label}</span>`}</div>`}).join('');const passed=captureResults.filter(x=>x.pass).length;const ready=Math.min(95,Math.round((passed/6)*80+Math.min(captureResults.length,12)/12*15));$('#fidelity-score').textContent=ready+'%';$('#quality-summary').textContent=`${passed} / 6`;$('#generate-twin').disabled=passed<6;$('#scan-progress').style.setProperty('--progress',ready+'%');$('#scan-progress span').textContent=passed>=6?(lang==='en'?'Capture set passed. Ready for secure upload.':'采集素材已通过，可以安全上传。'):(lang==='en'?`${6-passed} required view(s) still need a clear image`:`还有 ${6-passed} 个必需视角需要清晰图片`);const checks=lang==='en'?[['Resolution',captureResults.some(x=>x.resolution)],['Lighting',captureResults.some(x=>x.brightness)],['Sharpness',captureResults.some(x=>x.sharp)],['Coverage',captureResults.length>=6]]:[['分辨率',captureResults.some(x=>x.resolution)],['光线',captureResults.some(x=>x.brightness)],['清晰度',captureResults.some(x=>x.sharp)],['视角覆盖',captureResults.length>=6]];$('#quality-checks').innerHTML=checks.map(([name,ok])=>`<span class="${ok?'pass':''}">${ok?'✓':'○'} ${name}</span>`).join('')}
function inspectImage(file){return new Promise(resolve=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas'),size=96;canvas.width=canvas.height=size;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,size,size);const data=ctx.getImageData(0,0,size,size).data;let light=0,edges=0;for(let y=1;y<size-1;y+=2)for(let x=1;x<size-1;x+=2){const i=(y*size+x)*4,l=(data[i]+data[i+1]+data[i+2])/3;light+=l;const j=(y*size+x+1)*4;edges+=Math.abs(l-(data[j]+data[j+1]+data[j+2])/3)}const samples=((size-2)/2)*((size-2)/2),avg=light/samples,sharp=edges/samples>8,resolution=img.width>=900&&img.height>=900,brightness=avg>45&&avg<225;resolve({file,url,resolution,brightness,sharp,pass:resolution&&brightness&&sharp})};img.onerror=()=>resolve({file,url,resolution:false,brightness:false,sharp:false,pass:false});img.src=url})}
$('#pet-photo').onchange=async event=>{captureResults.forEach(x=>URL.revokeObjectURL(x.url));captureResults=await Promise.all([...event.target.files].slice(0,40).map(inspectImage));renderCaptureSlots()};
$('#start-scan').onclick=()=>{let p=0;$('#scan-progress span').textContent=lang==='en'?'Guide: keep Mochi still and walk slowly around the full body.':'引导：让 Mochi 保持不动，缓慢绕全身拍摄。';const timer=setInterval(()=>{p+=5;$('#scan-progress').style.setProperty('--progress',p+'%');if(p>=95){clearInterval(timer);$('#scan-progress span').textContent=lang==='en'?'Scan route complete. Add the captured frames to continue.':'扫描路线完成，请添加拍摄的画面以继续。'}},100)};
$$('[data-capture-mode]').forEach(b=>b.onclick=()=>{$$('[data-capture-mode]').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.captureMode==='scan')$('#start-scan').focus()});
function loadGlb(file){if(!window.THREE||!THREE.GLTFLoader)return;const url=URL.createObjectURL(file),loader=new THREE.GLTFLoader();$('#studio-result').textContent=lang==='en'?'Loading reconstructed model…':'正在载入重建模型…';loader.load(url,gltf=>{worldScene.remove(petGroup);petGroup=new THREE.Group();const model=gltf.scene,box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),scale=2.1/Math.max(size.x,size.y,size.z);model.position.sub(center);model.scale.setScalar(scale);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});petGroup.add(model);worldScene.add(petGroup);headMesh=tailMesh=null;legs=[];if(gltf.animations.length){modelClock=new THREE.Clock();modelMixer=new THREE.AnimationMixer(model);modelMixer.clipAction(gltf.animations[0]).play()}$('#model-source').textContent=lang==='en'?'Reconstructed GLB':'重建 GLB 模型';$('#studio-result').textContent=lang==='en'?'Model loaded. Texture, shape and animation are active.':'模型已载入，纹理、形体和动画均已启用。';URL.revokeObjectURL(url)},undefined,()=>{$('#studio-result').textContent=lang==='en'?'This GLB could not be read. Please export as GLB 2.0.':'无法读取该模型，请导出为 GLB 2.0。';URL.revokeObjectURL(url)})}
$('#glb-file').onchange=e=>{if(e.target.files[0])loadGlb(e.target.files[0])};
$('#generate-twin').onclick=async()=>{const stages=$$('#reconstruction-pipeline span');stages.forEach(x=>x.classList.remove('active'));$('#generate-twin').disabled=true;for(let i=0;i<stages.length;i++){stages[i].classList.add('active');$('#scan-progress').style.setProperty('--progress',(20+i*19)+'%');$('#studio-result').textContent=lang==='en'?['Encrypting and uploading captures…','Reconstructing body geometry…','Projecting coat texture…','Preparing motion rig…','Creating review model…'][i]:['正在加密上传素材…','正在重建身体形体…','正在投射毛发纹理…','正在生成动作骨骼…','正在创建验收模型…'][i];await new Promise(r=>setTimeout(r,550))}$('#studio-result').textContent=lang==='en'?'Demo job prepared. Connect the reconstruction API to receive the final GLB.':'演示任务已准备好，连接重建 API 后即可接收最终 GLB。';$('#generate-twin').disabled=false};
renderCaptureSlots();

applyLanguage();initTwin();
if(!state.twinVisible){
  $('#pet-world').style.display='none';
  $('#pet-message').classList.add('hidden');
  $('#pet-toggle').textContent=t('showTwin');
}

